# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Paul E. Reed, Ph.D
email: pereed1@ua.edu
description: > # this means to ignore newlines until "baseurl:"
  I am an assistant professor in the Department 
  of Communicative Disorders at the University of Alabama. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: perj44
github_username:  paulereed

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
job.title: "Assistant Professor"
excerpt_separator: "<!--more-->"

#gems:
#  - jekyll-sitemap